name: Markdown Lint

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  rumdl-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: rvben/rumdl@a2da0e5a1321281402d4c65f5b735696a7f5f73f # v0.2.16
